# ~/.config/starship.toml
format = """
$username\
$os\
$git_branch\
$git_status\
$python\
$lua\
$c\
\n$character
"""

[username]
style_user = 'white bold'
style_root = 'black bold'
# format = 'user: [$user]($style) '
format = '[$user]($style) [at](green) [lkr](bold) '
# format = '[$user]($style) [at](green) [Arch Linux](bold) '
disabled = false
show_always = true

[buf]
symbol = " "

[c]
symbol = " "

[directory]
read_only = " 󰌾"

[docker_context]
symbol = " "

[git_branch]
symbol = " "

[git_status]
conflicted = '$count='
ahead = '$count⇡'
behind = '$count⇣'
diverged = '$count⇕'
# up_to_date = '✓{$count}'
up_to_date = '✓'
untracked = '$count?'
stashed = '$count+'
modified = '$count!'
staged = '[++\($count\)](green)'
renamed = '$count”'
deleted = '$count✘'

[hostname]
ssh_symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "
disabled = false
threshold = -1
style = 'bold dimmed green'

[jobs]
symbol = '+ '
number_threshold = 4
symbol_threshold = 0

[os]
format = "on [($name )]($style)"
style = "bold blue"
disabled = false

[os.symbols]
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = "󰍲 "

[python]
symbol = " "

[character]
success_symbol = '[◯](bold green)'
